stage: train
seed: 0
accelerator: cpu
devices: -1
huggingface_cache_dir: null
checkpoint_output_dir: output/checkpoints
defaults:
  - datasets:
      - cc100
      - treebank
  - datamodule: masked-language-modeling
  - model: bert-base
  - task: masked-language-modeling
  - scheduler: linear-with-warmup
  - _self_