stage: train
seed: 0
huggingface_cache_dir: null
defaults:
  - datasets:
      - cc100
      - treebank
  - datamodule: masked-language-modeling
  - model: bert-base
  - task: masked-language-modeling
  - _self_