stage: train
seed: 0
accelerator: cpu
devices: -1
huggingface_cache_dir: null
checkpoint_output_dir: output/checkpoints
profiler: null
defaults:
  - datasets:
      - cc100
      - culturax
      - treebank
      - ukrcorpus
  - datamodule: masked-language-modeling
  - model: bert-base
  - task: masked-language-modeling
  - optimizer: adamw
  - scheduler: linear-with-warmup
  - _self_