name: masked-language-modeling
datasets:
  train:
    - cc100
  val:
    - treebank
batch_size: 96
num_workers: 4
pin_memory: false
tokenizer_path: research/tokenizer/experiment-5-overall-v2
prefetch_factor: 2
multiprocessing_context: spawn
